# This file was generated by GoReleaser. DO NOT EDIT.
cask "tlscensus" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "7b1997b1e66af5471821016705bfb45d6c404bedc66f831f05ef13a3bc44f8d3"
      url "https://github.com/connectedinformation/tlscensus/releases/download/v#{version}/tlscensus_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9d53d803c7191fec8789ac44fccff28840214b6dee4b077baf0bac1ac73e9761"
      url "https://github.com/connectedinformation/tlscensus/releases/download/v#{version}/tlscensus_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "aeb8c3d240615327f6b5c97d476e7e8b3d384b05d574540946a3cffde69e853e"
      url "https://github.com/connectedinformation/tlscensus/releases/download/v#{version}/tlscensus_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0621a89c2ae685ead67fd8f0041fa75d24b41f0faf1b3182c39664705e8266d8"
      url "https://github.com/connectedinformation/tlscensus/releases/download/v#{version}/tlscensus_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tlscensus"
  desc "Passive TLS cryptography inventory"
  homepage "https://github.com/connectedinformation/tlscensus"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tlscensus"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tlscensus"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Reading capture files needs no privileges:

        tlscensus read capture.pcap

    Live capture reads /dev/bpf*, which is root-only by default:

        sudo tlscensus watch

    To capture without running the whole tool as root, put yourself in the
    access_bpf group as Wireshark does. See:
    https://github.com/connectedinformation/tlscensus/blob/main/docs/permissions.md
  EOS
end
