# This file was generated by GoReleaser. DO NOT EDIT.
cask "tlscensus" do
  version "0.1.0-rc1"

  on_macos do
    on_arm do
      sha256 "10790e7a0d0876e103600375d926c8b0b8ad2a97142f5b4695d7b689af45a458"
      url "https://github.com/connectedinformation/tlscensus/releases/download/v#{version}/tlscensus_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c41c6e4b231005a3c135c403f28e7750993802f464b39d979dd4f476831dd190"
      url "https://github.com/connectedinformation/tlscensus/releases/download/v#{version}/tlscensus_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "55cb6a3e9c3d6b1134fb44243f67826ce62ba2fbc0c5fe8507da0460905b37b8"
      url "https://github.com/connectedinformation/tlscensus/releases/download/v#{version}/tlscensus_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3f596208d0c627fd2fd71dfd96036be383027746ac388f19062458dfaa847614"
      url "https://github.com/connectedinformation/tlscensus/releases/download/v#{version}/tlscensus_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tlscensus"
  desc "Passive TLS cryptography inventory"
  homepage "https://github.com/connectedinformation/tlscensus"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tlscensus"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tlscensus"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Reading capture files needs no privileges:

        tlscensus read capture.pcap

    Live capture reads /dev/bpf*, which is root-only by default:

        sudo tlscensus watch

    To capture without running the whole tool as root, put yourself in the
    access_bpf group as Wireshark does. See:
    https://github.com/connectedinformation/tlscensus/blob/main/docs/permissions.md
  EOS
end
