# This file was generated by GoReleaser. DO NOT EDIT.
cask "tlscensus" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "2539fb661ec76b4625b11a0e052608cb93bf627c63d41cc43946fa019a9c05b4"
      url "https://github.com/connectedinformation/tlscensus/releases/download/v#{version}/tlscensus_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1f45a1e35a5784dbeec237950ae601e0b36e530e45658eca7ecd7a5dbdff83a3"
      url "https://github.com/connectedinformation/tlscensus/releases/download/v#{version}/tlscensus_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f6e69cfc4ee2407e6813cc77f259222f2ce55f5deafa680746006022afe1ae0d"
      url "https://github.com/connectedinformation/tlscensus/releases/download/v#{version}/tlscensus_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "553d6303fccba812977129c40767bea5f87b3e29285401730857d6ff785d4866"
      url "https://github.com/connectedinformation/tlscensus/releases/download/v#{version}/tlscensus_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tlscensus"
  desc "Passive TLS cryptography inventory"
  homepage "https://github.com/connectedinformation/tlscensus"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tlscensus"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tlscensus"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Reading capture files needs no privileges:

        tlscensus read capture.pcap

    Live capture reads /dev/bpf*, which is root-only by default:

        sudo tlscensus watch

    To capture without running the whole tool as root, put yourself in the
    access_bpf group as Wireshark does. See:
    https://github.com/connectedinformation/tlscensus/blob/main/docs/permissions.md
  EOS
end
